import Head from "next/head";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Layout from "@/app/components/common/Layout";
import {IPlace} from "@/app/type/place.type";
import {NextPage} from "next";
import {GetStaticProps} from "next";
import HeadingSection from "@/app/components/elements/home/headingSection/HeadingSection";
import Search from "@/app/components/common/search/Search";
import Filters from "@/app/components/elements/filters/Filters";
import {API_URL} from "@/app/constants";
import PopularPlaces from "@/app/components/elements/home/popularPlaces/PopularPlaces";
import {useState} from "react";

const inter = Inter({subsets: ["latin"]});

interface IHome {
    initialPlaces: IPlace[]
}

const Home: NextPage<IHome> = ({initialPlaces}) => {
    const [places, setPlaces]=useState<IPlace[]>(initialPlaces);
    const [isLoading,setIsLoading]=useState(false);

    return (
        <>
            <Head>
                <title>Travelio</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout className={`${styles.main} ${inter.className}`}>
                <HeadingSection/>
                <div className={styles.content}>
                    <Search setPlaces={setPlaces} initialPlaces={initialPlaces} setIsLoading={setIsLoading}/>
                    <Filters setPlaces={setPlaces}/>
                    <PopularPlaces places={places} isLoading={isLoading}/>
                </div>
            </Layout>
        </>
    );
}

export const getStaticProps: GetStaticProps =
    async () => {
        const result = await fetch(`${API_URL}/places`);
        const initialPlaces: IPlace[] = await result.json();
        return {
            props: {
                 initialPlaces
            }
        }
    };

export default Home;
