import Head from "next/head";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Layout from "@/app/components/common/Layout";
import {IPlace} from "@/app/type/place.type";
import {NextPage} from "next";
import {GetStaticProps} from "next";
import SearchSection from "@/app/components/elements/searchSection/SearchSection";

const inter = Inter({subsets: ["latin"]});

interface IHome {
    places: IPlace[]
}

const Home: NextPage<IHome> = ({places}) => {
    return (
        <>
            <Head>
                <title>Travelio</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout className={`${styles.main} ${inter.className}`}>
                <SearchSection/>
            </Layout>
        </>
    );
}

export const getStaticProps: GetStaticProps =
    async () => {
        const result = await fetch('http://localhost:3000/api/places');
        const places: IPlace[] = await result.json();
        return {
            props: {
                places
            }
        }
    };

export default Home;
